[package]
name = "clippy-control"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rx.workspace = true
rx.features = [
]

[[bin]]
name = "clippy-control"
path = "src/main.rs"
