[package]
name = "clippy-control"
description.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true

[[bin]]
name = "clippy-control"
path = "src/main.rs"
